#! /bin/sh

# If we know the boot interface and there is nothing in /etc/network/interfaces.d,
# configure it to bring up networking using DHCP

set -e

if [ "$1" = "prereqs" ]; then
	exit 0
fi

# This requires the 'IPAPPEND 2' option line in the PXE config block
if [ -n "$BOOTIF" ] && [ -z "$(ls ${rootmnt}/etc/netplan)" ]; then
	bootif_mac="$(echo "${BOOTIF#01-}" | busybox tr - :)"
	# look for devices with matching mac address, and set DEVICE to
	# appropriate value if match is found.
	DEVICE=
	for device in /sys/class/net/* ; do
		if [ -f "$device/address" ]; then
			if [ "$bootif_mac" = $(cat "$device/address") ]; then
				DEVICE=${device##*/}
				break
			fi
		fi
	done
	if [ -n "$DEVICE" ]; then
		cat > ${rootmnt}/etc/netplan/bootif <<EOF
network:
    version: 2
    renderer: networkd
    ethernets:
        $DEVICE:
            dhcp4: true
EOF
	fi
fi

exit 0
